PROPERTIES = [
    {
        "name": "Jovie Belterra",
        "website": "https://livejoviebelterra.com/",
        "apartments_com": "https://www.apartments.com/jovie-belterra-austin-tx/389zg9g/",
        "facebook": "https://www.facebook.com/livejoviebelterra/",
        "google_place_name": "Jovie Belterra Apartments",
    },
    {
        "name": "The Bower",
        "website": "https://theboweratx.com/",
        "apartments_com": "https://www.apartments.com/the-bower-pflugerville-tx/kd29x49/",
        "facebook": "https://www.facebook.com/p/The-Bower-61573405531961/",
        "google_place_name": "The Bower Apartments Pflugerville",
    },
    {
        "name": "Brio",
        "website": "https://livebrioapartments.com/",
        "apartments_com": "https://www.apartments.com/brio-pflugerville-tx/wm7lbxj/",
        "facebook": "https://www.facebook.com/BrioPflugerville/",
        "google_place_name": "Brio Apartments Pflugerville",
    },
    {
        "name": "Local Dripping Springs",
        "website": "https://localdrippingsprings.com/",
        "apartments_com": "https://www.apartments.com/local-dripping-springs-dripping-springs-tx/l41kn2g/",
        "facebook": "https://www.facebook.com/p/Local-Dripping-Springs-Apartments-61564532957384/",
        "google_place_name": "Local Dripping Springs Apartments",
    },
    {
        "name": "Jovie Lakeway",
        "website": "https://www.jovielakeway.com/",
        "apartments_com": "https://www.apartments.com/jovie-lakeway-lakeway-tx/tfc1zk8/",
        "facebook": "https://www.facebook.com/JovieLakeway/",
        "google_place_name": "Jovie Lakeway Apartments",
    },
    {
        "name": "Sommery",
        "website": "https://livesommery.com/",
        "apartments_com": "https://www.apartments.com/the-sommery-round-rock-tx/282lmzc/",
        "facebook": "https://www.facebook.com/profile.php?id=61576123096959",
        "google_place_name": "The Sommery Apartments Round Rock",
    },
    {
        "name": "Jolie",
        "website": "https://jolieapts.com/",
        "apartments_com": "https://www.apartments.com/jolie-pflugerville-pflugerville-tx/pb6zsfs/",
        "facebook": "https://www.facebook.com/joliepflugerville/",
        "google_place_name": "Jolie Apartments Pflugerville",
    },
]
